version: "3"
services:

  redis:
    image: redis:alpine
    ports:
      - "6379"
    networks:
      - backend
  db:
    image: mongo
    environment:
      - MONGO_DATA_DIR=/data/db
    volumes:
      - db-data:/data/db
    networks:
      - backend
  app:
    build: .
    ports:
      - 3000:3000
    environment:
      - DEBUG=*
    env_file:
      - .env
    networks:
      - backend
    depends_on:
      - redis
      - db

networks:
  backend:

volumes:
  db-data:
